server:
  port: 8086
  forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      routes:
        - id: catalogue-service-route
          uri: http://172.17.0.1:8081
          predicates:
            - Host=**.catalogue.api.bfu.com.172.17.0.1.nip.io**
        - id: cart-service-route
          uri: http://172.17.0.1:8083
          predicates:
            - Host=**.cart.api.bfu.com.172.17.0.1.nip.io**
        - id: feedback-service-route
          uri: http://172.17.0.1:8084
          predicates:
            - Host=**.feedback.api.bfu.com.172.17.0.1.nip.io**
        - id: order-service-route
          uri: http://172.17.0.1:8085
          predicates:
            - Host=**.order.api.bfu.com.172.17.0.1.nip.io**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/eshop
        registration:
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: aOwBUK7tKcRU4ne0GsMsawoYmkuOhTY5
            authorization-grant-type: client_credentials
            scope:
              - discovery
eureka:
  client:
    enabled: false