spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/realms/eshop/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/eshop
        registration:
          api-gateway:
            provider: keycloak
            client-id: api-gateway
            client-secret: GwYWx4TEXh7XV8KtGpjklaUWkim7uQ99
            authorization-grant-type: authorization_code
            scope: openid
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: catalogue-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/catalogue/**
        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/cart/**