server:
  port: 8083
spring:
  application:
    name: order_service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: order
    password: order
  flyway:
    schemas:
      - public
      - orderService
  jpa:
    show-sql: true

