server:
  port: 8085
spring:
  application:
    name: order_service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: order
    password: order
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/eshop
  flyway:
    schemas:
      - public
      - order_service
  jpa:
    show-sql: true

