server:
  port: 8081
spring:
  application:
    name: catalogue-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: catalogue
    password: catalogue
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/eshop

  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true