eshop:
  services:
    feedback:
      uri: lb://feedback-service
      registration-id: keycloak
server:
  port: 8081
spring:
  application:
    name: catalogue-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: catalogue
    password: catalogue
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/eshop
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: catalogue-service
            client-secret: CtECQIuXX1q3oeQPHbxrHaFSFOW8i0mV
            authorization-grant-type: client_credentials
            scope:
              - openid
          discovery:
            provider: keycloak
            client-id: catalogue-service
            client-secret: CtECQIuXX1q3oeQPHbxrHaFSFOW8i0mV
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/eshop

  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
springdoc:
  swagger-ui:
    oauth:
      client-id: catalogue-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true