server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8082/realms/eshop
        registration:
          keycloak:
            client-id: eureka-server
            client-secret: JmRZsTenKVxSZ1BQbbnIQ8yazixNZjl6
            scope:
              - openid
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/eshop