eshop:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
server:
  port: 8083
spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/cart-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/eshop
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: customer-service
            client-secret: lrdajFhHOhP9ubIZJ8Na3RlnIYFoAvzZ
            authorization-grant-type: client_credentials
            scope:
              - openid
          discovery:
            provider: keycloak
            client-id: customer-service
            client-secret: lrdajFhHOhP9ubIZJ8Na3RlnIYFoAvzZ
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/eshop
keycloak:
  uri: http://localhost:8082
springdoc:
  swagger-ui:
    oauth:
      client-id: cart-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true