server:
  port: 8083
spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/cart-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/eshop