server:
  port: 8084
spring:
  application:
    name: feedback-service
  data:
    mongodb:
      uri: mongodb://localhost:27028/feedback-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/eshop